name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0   # evita warning de git 128

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
        cache: maven

    - name: Build & Test (with coverage)
      run: mvn -B -ntp clean verify

    - name: Upload JaCoCo report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: target/site/jacoco/**
